@DataExtractor_HostAddress = http://localhost:5161
# @DataExtractor_HostAddress = https://kemorsky.github.io/Data-Extractor/

GET {{DataExtractor_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{DataExtractor_HostAddress}}/
Accept: application/json

###

GET {{DataExtractor_HostAddress}}/mod-data
Accept: application/json

###

GET {{DataExtractor_HostAddress}}/locations
Accept: application/json

###

GET {{DataExtractor_HostAddress}}/test
Accept: application/json

###

GET {{DataExtractor_HostAddress}}/locations/Anga
Accept: application/json

###

GET {{DataExtractor_HostAddress}}/locations/filter?parentLocation=County-Anvil
Accept: application/json

###