name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0'

      # Download ESM files
      # -------------------------

      - name: Install 7zip
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: Download ESM files
        run: | 
          mkdir -p plugins

          curl --fail --location \
            'https://drive.usercontent.google.com/download?id=112DA5AgbjPT0B0ufbxW7wkguMoxx4fhf&export=download&confirm=t' \
            --output plugins/Plugins.7z

          7z x plugins/Plugins.7z -oplugins -y
          rm plugins/Plugins.7z

          cp plugins/*.esm .

          curl --fail --location \
            --header "PRIVATE-TOKEN: ${{ secrets.TOKEN }}" \
            "https://gitlab.beyondskyrim.org/api/v4/projects/34/repository/files/BSAssets.esm/raw" \
            --output plugins/BSAssets.esm

          curl --fail --location \
            --header "PRIVATE-TOKEN: ${{ secrets.TOKEN }}" \
            "https://gitlab.beyondskyrim.org/api/v4/projects/35/repository/files/BSHeartland.esm/raw" \
            --output plugins/BSHeartland.esm

      # Build and run extractor
      # -------------------------

      - name: Restore extractor tool
        run: dotnet restore DataExtractor.Tool/DataExtractor.Tool.csproj    
      
      - name: Build extractor tool
        run: dotnet build DataExtractor.Tool/DataExtractor.Tool.csproj --configuration Release --no-restore

      - name: Test extractor tool
        run: dotnet test DataExtractor.Tool/DataExtractor.Tool.csproj --configuration Release --no-build --verbosity normal

      - name: Run extractor tool
        run: |
          dotnet run \
            --project DataExtractor.Tool/DataExtractor.Tool.csproj \
            --configuration Release

      - name: Verify generated data
        run: |
          ls -lh DataExtractor/Data/locations.json
          head -c 500 DataExtractor/Data/locations.json


      # Build and run backend
      # -------------------------

      - name: Restore
        run: dotnet restore DataExtractor/DataExtractor.csproj    
      
      - name: Build
        run: dotnet build DataExtractor/DataExtractor.csproj --configuration Release --no-restore

      - name: Test
        run: dotnet test DataExtractor/DataExtractor.csproj --configuration Release --no-build --verbosity normal

      # - name: Generate data
      #   run: |
      #     dotnet run \
      #       --project DataExtractor/DataExtractor.csproj \
      #       --configuration Release

      - name: Publish backend
        run: dotnet publish DataExtractor/DataExtractor.csproj -c Release -o publish  


        
          
